[package]
name = "ispm"
version = "0.1.0"
authors = ["Peter PJT <pjtsignups@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yaml-rust = "0.4.4"
shell = { git = "https://github.com/google/rust-shell" }